Atualização dos dados do livro do Nilo Ney.
pythonbrasil/wiki pull request #200
Opened 2019-10-04 18:33 UTC by HortenciaArliane

Contribuição para issue #61 .

2019-11-25 10:01 UTC, cadu-leite commented
Após aceitar outros PRs, 
este passou a conflitar. Por favor @HortenciaArliane revise para nós. 
e obrigado pela PR...     
v ficar de olho para nào demorar tanto o review. ;)

2019-11-30 13:05 UTC, cadu-leite commented
este PR poderia ser quebrado em 2 ou 3 ...  facilitaria muito!

2019-12-01 00:41 UTC, HortenciaArliane commented
Boa noite, Cadu! Bem, eu não entendi o porquê da necessidade de dividir este PR em outros PRs. Até porque, os commits estão com o mesmo contexto,  ou seja, poderia me explicar melhor?. E em relação ao conflito, será que poderia me exclarecer exatamente o problema para mim resolvê-lo?

2020-01-24 14:56 UTC, adorilson commented
> E em relação ao conflito, será que poderia me exclarecer exatamente o problema para mim resolvê-lo?

@cadu-leite , poderia falar algo sobre esse ponto?

2020-06-14 18:49 UTC, cadu-leite commented
> Boa noite, @cadu-leite! Bem, eu não entendi o porquê da necessidade de dividir este PR em outros PRs. Até porque, os commits estão com o mesmo contexto, ou seja, poderia me explicar melhor?. E em relação ao conflito, será que poderia me exclarecer exatamente o problema para mim resolvê-lo?

Somente resolver os conflitos que estão sendo indicados aqui.

2024-10-17 09:04 UTC, adorilson commented
Resolvi o conflito e removi itens com links quebrados. Depois, abri uma issue para atualizar a lista de material #309

2024-10-17 10:23 UTC, naanadr requested changes

2024-10-17 10:23 UTC, naanadr commented on content/pages/introducao.md
>  **Que IDE usar?**
@adorilson você pode adicionar o VSCode na lista? Atualmente é uma das IDEs mais utilizadas.

2024-10-17 10:23 UTC, naanadr commented on content/pages/introducao.md
>  Isso é uma boa prática e pode evitar dores de cabeça futuras. [Dê uma lida](https://virtualenv.pypa.io/en/stable/) sobre antes de iniciar um projeto grande, ok?
Remover a referência do virtualenv e adicionar o [venv](https://docs.python.org/pt-br/3/library/venv.html).

2024-10-17 13:11 UTC, adorilson commented on content/pages/introducao.md
>  Isso é uma boa prática e pode evitar dores de cabeça futuras. [Dê uma lida](https://virtualenv.pypa.io/en/stable/) sobre antes de iniciar um projeto grande, ok?
Feito.

2024-10-17 13:12 UTC, adorilson commented on content/pages/introducao.md
>  **Que IDE usar?**
Feito. Acabei editando essa seção um pouco mais.

2024-10-17 13:30 UTC, naanadr approved these changes

2024-10-17 13:33 UTC, merged