Resolvendo conflitos da pagina de empresa e simplificando codigo do p…
pythonbrasil/wiki pull request #222
Opened 2019-11-25 19:58 UTC by fecaridade

Simplificando o codigo do pelicanconf.py deixando-o mais explicito.
Resolvendo problema gerado pelo #206 onde a página [`empresas`](https://python.org.br/empresas/) se encontrava quebrada

2019-11-25 19:59 UTC, fecaridade commented
Agora sim, tudo funcionando.
Desculpem qualquer erro de código deste jovem estágiario.

2019-11-26 02:21 UTC, luzfcb commented on pelicanconf.py
> +]
Sugiro deixar explicito o encoding na função open, e fechar o descritor após a leitura do arquivo.

```python
for fname in glob.glob('content/empresas/*.json')
    with open(fname, mode='r', encoding='utf-8') as arquivo:
        EMPRESAS.append(json.load(arquivo))
```

2019-11-26 02:26 UTC, cadu-leite commented on pelicanconf.py
> +]
> Sugiro deixar explicito o encoding na função open, e fechar o descritor após a leitura do arquivo.
> 
> ```python
> EMPRESAS = []
> for fname in glob.glob('content/empresas/*.json')
>     with open(fname, mode='r', encoding='utf-8') as arquivo:
>         EMPRESAS.append(json.load(arquivo))
> ```

um dos meu problemas hoje pela manhã ao rever a PR ;)  - mac !!

https://twitter.com/ramalhoorg/status/1199036224637456390?s=20
"""
In my opinion, using bytes.decode() without specifying an encoding is very bad practice and should not be allowed at all. I consider it a bug that bytes.decode() has a default encoding.
"

2022-03-14 19:19 UTC, rougeth requested changes

2022-03-14 19:19 UTC, rougeth commented on pelicanconf.py
> +# EMPRESAS = import_empresas('content/empresas/*.json')
```suggestion
```

2022-03-14 19:20 UTC, rougeth approved these changes

2022-03-14 19:20 UTC, merged

2022-03-14 19:20 UTC, rougeth commented on pelicanconf.py
> +# EMPRESAS = import_empresas('content/empresas/*.json')
Vou remover em um próximo PR.

2022-03-14 19:20 UTC, rougeth commented
Valeu @fecaridade!