Pagina grupos online
pythonbrasil/wiki pull request #301
Opened 2024-08-20 15:49 UTC by lskbr

Nova opção no menu participe para listas grupos de Telegram e do Discord fora dos grupos locais.

2024-08-22 11:52 UTC, adorilson commented on content/pages/gruposonline.md
> +
Pinguei o @rougeth no Discord para darmos um encaminhamento a isto.

2024-08-22 21:35 UTC, naanadr requested changes

2024-08-22 21:35 UTC, naanadr commented on content/pages/gruposonline.md
> +Estes grupos não são organizados pelo Associação Python Brasil.
Seria legal ter um hyperlink para o site da associação:

```suggestion
Estes grupos não são organizados pelo [Associação Python Brasil](https://apyb.python.org.br/).
```

2024-08-22 21:35 UTC, naanadr commented on content/pages/gruposonline.md
> +Os grupos listados abaixo são gerenciados e mantidos por iniciativas independentes da comunidade Python.
Seria legal deixar claro também que caso a pessoa queira que a iniciativa dela esteja listada nessa página, ela pode abrir um Pull Request nesse repositório.

2024-08-22 21:35 UTC, naanadr commented on content/pages/gruposonline.md
> +- [Engenharia de Dados](https://t.me/engenhariadadosbr)
```suggestion
- [Engenharia de Dados BR](https://t.me/engenhariadadosbr)
```

2024-08-22 21:35 UTC, naanadr commented on content/pages/gruposonline.md
> +## Telegram
Vários grupys, pugs, e eventos regionais tem grupo no telegram. Eles também deveriam estar aqui listados?

2024-08-22 21:35 UTC, naanadr commented on content/pages/gruposonline.md
> +- [Engenharia de Dados](https://t.me/engenhariadadosbr)
Será que ficaria melhor a visualização em tabela?

2024-08-23 07:00 UTC, lskbr commented on content/pages/gruposonline.md
> +- [Engenharia de Dados](https://t.me/engenhariadadosbr)
Meu talento visual é muito limitado :-D Imaginei a tabela com apenas uma coluna. Tens uma ideia do que poderíamos colocar como segunda coluna?

2024-08-29 22:21 UTC, naanadr commented on content/pages/gruposonline.md
> +- [Engenharia de Dados](https://t.me/engenhariadadosbr)
a segunda coluna poderia ser algum site, mas olhando agora esses grupos não são vinculados a comunidades que tem site ou algo externo 😆  então deixa para lá 🤣

2024-08-29 22:22 UTC, naanadr approved these changes

2024-08-29 22:22 UTC, naanadr commented
Vou esperar o @adorilson fazer o review dele para poder dar merge no PR 😄

2024-08-30 11:55 UTC, adorilson requested changes

2024-08-30 11:55 UTC, adorilson commented on content/pages/gruposonline.md
> +- [Engenharia de Dados BR](https://t.me/engenhariadadosbr)
Esse grupo não me parece ser de Python.

2024-08-30 11:55 UTC, adorilson commented on content/pages/gruposonline.md
> +<!-- ## Discord -->
Link para o https://discord.gg/TuENdUjwQX

2024-08-30 11:55 UTC, adorilson commented on content/pages/gruposonline.md
> +Caso você queira adicionar seu grupo Telegram ou servidor Discord, [faça um pull request no repositório desta wiki](https://github.com/pythonbrasil/wiki/).
Faria assim:

Caso você queira adicionar uma comunidade, [faça um pull request no repositório desta wiki](https://github.com/pythonbrasil/wiki/). Lembre-se que ela deve ser sobre o ecossistema Python.

2024-09-05 12:35 UTC, lskbr commented
Correções aplicadas:
- Retirado grupo de engenharia de dados
- Lembrete no final da página
- Link pro discord

2024-09-05 13:21 UTC, merged