Atualiza os contatos e a logo do PUG-PE
pythonbrasil/wiki pull request #308
Opened 2024-10-14 12:07 UTC by rochamatcomp

Em conversa com a Fernanda Souza no telegram da PUG-PE, ela pediu para fazer essa atualização para a comunidade de Pernambuco.

2024-10-14 14:01 UTC, adorilson approved these changes

2024-10-14 22:37 UTC, naanadr requested changes

2024-10-14 22:37 UTC, naanadr commented on content/comunidades-locais/pug-pe.json
> -            "https://groups.google.com/forum/#!forum/pug-pe"
Acho que vale deixar o link do Google Groups, porque a comunidade nasceu lá e tem muito histórico do que aconteceu.

2024-10-20 03:29 UTC, naanadr approved these changes

2024-10-20 03:29 UTC, merged